export const projectsData = [
  {
    id: 1,
    title: "AI Employee Solutions",
    description: "A cutting-edge SaaS platform designed to streamline human resources using AI-driven tools.",
    image: "/images/ai-employee-solutions.webp",
    category: "Technology",
    tags: ["React", "Squarespace", "AI"],
    slug: "ai-employee-solutions",
    client: "AI Employee Inc.",
    role: "Lead Developer",
    year: "2024",
    challenge: "Integrating complex AI models into a user-friendly frontend without sacrificing fast loading speeds or standard SEO benefits.",
    solution: "We meticulously built a custom API routing system paired with aggressive edge caching, seamlessly woven into the custom UI to provide instant feedback to end-users."
  },
  {
    id: 2,
    title: "Beginner's Mind Coaching",
    description: "A calming, content-rich hub for a professional life coach focused on mental clarity.",
    image: "/images/beginners-mind-coaching.webp",
    category: "Health & Wellness",
    tags: ["Web Design", "Branding"],
    slug: "beginners-mind-coaching",
    client: "Beginner's Mind LLC",
    role: "Full-Stack Designer",
    year: "2023",
    challenge: "Balancing a vast amount of written content from the coach while maintaining a minimalist, zen aesthetic that doesn't overwhelm the prospective client.",
    solution: "Implemented an elegant accordion-based layout, smooth scroll anchoring, and extensive whitespace to gently pace the reader's journey through the curriculum."
  },
  {
    id: 3,
    title: "Luminous Jewel",
    description: "An elegant e-commerce storefront for a high-end luxury jewelry brand.",
    image: "/images/luminous-jewel.webp",
    category: "E-commerce",
    tags: ["Squarespace Commerce", "UI/UX"],
    slug: "luminous-jewel",
    client: "Luminous Jewelers",
    role: "E-commerce Developer",
    year: "2025",
    challenge: "Showcasing ultra-high-resolution jewelry photography and complex product variants without severely lagging the mobile browsing experience.",
    solution: "Constructed a custom lazily-loaded gallery system. Paired with a high-contrast dark theme, the product images pop brilliantly without bloating the initial load."
  },
  {
    id: 4,
    title: "Monarch Inspection",
    description: "A robust corporate site for a regional property inspection company.",
    image: "/images/monarch-inspection.webp",
    category: "Business",
    tags: ["Corporate Design", "SEO"],
    slug: "monarch-inspection",
    client: "Monarch Group",
    role: "Web Designer",
    year: "2023",
    challenge: "Making a traditional, old-school industry look modern, trustworthy, and technologically advanced to new home buyers.",
    solution: "Integrated a custom multi-step lead-generation funnel, crisp SVG iconography, and professional, reliable typography to establish instant digital authority."
  },
  {
    id: 5,
    title: "The Real Pizza Face",
    description: "A bold, vibrant local pizzeria ordering site with mouth-watering visuals.",
    image: "/images/the-real-pizza-face.webp",
    category: "E-commerce",
    tags: ["Restaurant", "E-commerce"],
    slug: "the-real-pizza-face",
    client: "Pizza Face Pizzeria",
    role: "Web Developer",
    year: "2024",
    challenge: "Streamlining the online ordering menu to drastically reduce friction for hungry customers attempting to order quickly on mobile devices.",
    solution: "Customized the native commerce flow with a dedicated, sticky cart menu and an immersive, image-forward menu layout optimized entirely for thumbs."
  },
  {
    id: 6,
    title: "Digital Wellness Day",
    description: "A global initiative portal promoting healthy relationships with digital technology.",
    image: "/images/digital-wellness-day.webp",
    category: "Health & Wellness",
    tags: ["Event", "Landing Page"],
    slug: "digital-wellness-day",
    client: "Digital Wellness Inst.",
    role: "Lead Consultant",
    year: "2024",
    challenge: "Handling massive traffic spikes during the global event day and managing a complex ambassador registration loop flawlessly.",
    solution: "Utilized an external Firebase connection for real-time form registrations to bypass CMS limitations and guarantee zero database bottlenecks when traffic surged."
  },
  {
    id: 7,
    title: "Tristone Commercial",
    description: "An authoritative real estate portfolio for high-value commercial properties.",
    image: "/images/tristone-commercial.webp",
    category: "Business",
    tags: ["Real Estate", "CMS"],
    slug: "tristone-commercial",
    client: "Tristone CRE",
    role: "Developer",
    year: "2023",
    challenge: "Creating an easily maintainable, yet highly visual property inventory system for non-technical staff to update weekly.",
    solution: "Engineered a highly customized CMS logic architecture that auto-generates stunning, consistent grid layouts the moment staff types in the data."
  },
  {
    id: 8,
    title: "SaaS Website Kit",
    description: "A high-conversion template and framework tailored for SaaS startups.",
    image: "/images/saas-website.webp",
    category: "Technology",
    tags: ["Framer", "Template"],
    slug: "saas-website",
    client: "Internal Product",
    role: "Creator",
    year: "2025",
    challenge: "Designing a universally appealing framework that possesses enough rigid structure to convert, yet remains wildly flexible for diverse sub-niches.",
    solution: "Created a strict, component-driven design system with easily swappable CSS variables allowing brands to overhaul the entire site's vibe with three hex codes."
  },
  {
    id: 9,
    title: "Coach Dave",
    description: "A personal branding site for an energetic, results-driven fitness and life coach.",
    image: "/images/coach-dave.webp",
    category: "Health & Wellness",
    tags: ["Personal Brand", "Design"],
    slug: "coach-dave",
    client: "Dave Stevens",
    role: "Designer",
    year: "2024",
    challenge: "Capturing the client's immense IRL high energy virtually without the website feeling chaotic, overly busy, or overwhelming.",
    solution: "Deployed aggressive, bold typography, rigid structural whitespace to act as a dam for the energy, and punchy, action-oriented copywriting layouts."
  },
  {
    id: 10,
    title: "Bow Wow Vows",
    description: "A charming, specialized service that brings your dog to your wedding day.",
    image: "/images/bow-wow-vows.webp",
    category: "Services",
    tags: ["Niche", "Branding"],
    slug: "bow-wow-vows",
    client: "Bow Wow Vows",
    role: "Designer",
    year: "2023",
    challenge: "Balancing the premium luxury of a wedding service with the inherently warm, playful, and informal nature of a pet business.",
    solution: "Harmonized beautiful soft pastels, subtle playful micro-interactions, and deeply elegant, premium wedding-tier photography."
  }
];
